### ISSUE TITLE
Window-local histories?

### ISSUE THREAD

**Issue by dgutov** [boyw165/history#1]
I'd really prefer if the history wasn't stored in a global variable, but in a window parameter. Then you can have different histories in different windows (for separate trains of thought).

Here's an example implementation:
https://github.com/dgutov/point-stack/blob/master/point-stack.el#L83-L94

**Comment by tcw165** [comment]
Hi @dgutov , Good point! You mean every window (not frame) has its own history so a new window will have an empty history which doesn't inherit from a global history? Can you show me some cases of its benefit?

How about if there's a customization variable which let you choose GLOBAL or WINDOW-LOCAL history database? 
(implementing refer to your `point-stack`)

**Comment by tcw165** [comment]
Hi @dgutov ,

I just submitted the new feature, `history-window-local-history` in the latest repo. Hope you enjoy it~

**Comment by dgutov** [comment]
Works fine, thanks!

> a new window will have an empty history which doesn't inherit from a global history?

Right, I don't see a lot of benefits for inheriting. In window-local model, it won't be very intuitive behavior.

> Can you show me some cases of its benefit?

I'm going to before-advice several navigation commands with a call `history-add-history`. Then, imagine two windows, each displaying a different source file: I do a `find-function` in one of them, then do that again in the newly displayed buffer. Then I do the same (but along a different call chain) in the second window.

If the history is window-local, that allows me to jump back and forth along the code execution paths in both windows, in parallel.
