### ISSUE TITLE
Allow better control over ignored buffers.

### ISSUE THREAD

**Issue by rylimaki** [boyw165/history#12]
Following code is repeated in two locations to determine whether a buffer can be marked:

``` lisp
(dolist (ignore history-ignore-buffer-names)
    (when (string-match ignore (buffer-name))
```

Relocate the code into a function such as ignore-buffer? so that users can advice it.

I want to preserve current functionality, but make an exception for *ielm* buffer.

**Comment by tcw165** [comment]
Thank you, could you fire a PR? Or you'd prefer I to add the codes.

**Comment by rylimaki** [comment]
I can do that, but it will take a couple of days.
