### ISSUE TITLE
WishList: Integration with ctags/etags built-in tools

### ISSUE THREAD

**Issue by tcw165** [boyw165/history#3]
Is it possible to integrate `history` tool with ctags/etags built-in tools.

**Comment by tcw165** [comment]
Just add a new feature, `history-switch-buffer-history` to let you add history automatically when switching buffer (a switch).﻿

**Comment by dgutov** [comment]
You can just have a list of functions that would be before-advised with `history-add-history` (when the user calls a specific setup function, look at `point-stack` for the example).

Is there a point in offering specific support for different commands?

**Comment by tcw165** [comment]
Ok, I'll check it out.

> Is there a point in offering specific support for different commands?

What command?

**Comment by dgutov** [comment]
> What command?

Like `switch-to-buffer`.

**Comment by tcw165** [comment]
@dgutov 

> Is there a point in offering specific support for different commands?

Your `point-stack` teaches me a lot! I'll implement the advised functions list after applying it to my another repo, https://github.com/boyw165/hl-anything.
I'm wondering using after-advised function will get better performance than using idle timer. Do you have any idea?

```
(defcustom point-stack-advised-functions
  '(isearch-mode find-function-do-it find-library
    imenu beginning-of-buffer end-of-buffer
    xref-find-definitions)
  "Functions that will be advised by `point-stack-setup-advices'."
  :group 'point-stack)
```

**Comment by tcw165** [comment]
Hi @dgutov , just finished hook point. Enjoy~

**Comment by dgutov** [comment]
Thanks, but "hooks" it's not really the right term, so it might be confusing for people familiar with the Emacs ecosystem. Advices are really the inverse of hooks.

**Comment by dgutov** [comment]
Also, `history-add-after-functions` doesn't really seem useful.

EDIT: Scratch that. It could be.

**Comment by tcw165** [comment]
Ya I know it should be "advised" in Emacs ecosystem. I just want it to be much easier understanding for beginners. But I think it's better to give it a right name~ Fixed at https://github.com/boyw165/history/commit/af00b6d4c2efac375e9ccefb8ce8c0859a6ec3e8

> Also, history-add-after-functions doesn't really seem useful.

It is useful indeed. Actually every two contiguous histories are supposed to be a pair, like `from` and `to` entries. For instance, add history before `find-tag-noselect` and after `find-tag-noselect`.

**Comment by boyw165** [comment]
> Also, history-add-after-functions doesn't really seem useful.

It is useful indeed. Actually every two histories are pairs, like `from` and `to` entries.

**Comment by dgutov** [comment]
> For instance, add history before find-tag-noselect and after find-tag-noselect.

Ah, I see where you're going with this. Could you maybe adopt a feature from `point-stack` instead?

I've just noticed that this is missing: when I use `history-prev-history`, I'd always like to be able to call `history-next-history` and get right to where I was previously. `point-stack` implements that by having two histories: backward and forward ones. So when I go back, I push the current location to the "forward" stack first.

**Comment by tcw165** [comment]
Hmm, ok I'll update later. Maybe I don't need to implement whole backward and forward mechanism. Just to add a temporary entry (a counter in it, will be deleted when counting to zero; `history-delete-invalid-histories` will take the counting job).

**Comment by dgutov** [comment]
I don't really understand the suggestion, but it seems like the following won't work with it:

`M-x history-prev-history`
`M-x history-prev-history`
`M-x history-next-history`
`M-x history-next-history`

**Comment by tcw165** [comment]
Hi @dgutov , plz check [#e6ad5e24](https://github.com/boyw165/history/commit/4f7537936451f8d94c53972acf6949f5e6ad5e24) commit if it is the feature you want. :+1: 

Now it will add a temporary history entry implicitly if current point is far away from the current history. There'll be only one temporary history simultaneously.

![screen shot 2015-01-13 at 6 05 04 pm](https://cloud.githubusercontent.com/assets/6766554/5719013/c6fab9a0-9b4e-11e4-8414-c37556f76a53.png)
The history with underline indicates it is a temporary history.

**Comment by dgutov** [comment]
> check #e6ad5e24 commit if it is the feature you want.

Thanks! Not exactly what I asked, but it seems good enough. I'll have to test it for some time.
