### ISSUE TITLE
Question: Is this similar to back-button.el ?

### ISSUE THREAD

**Issue by shankarpdy** [boyw165/history#4]

**Comment by dgutov** [comment]
Apparently so. But that package works with `global-mark-ring`, whereas this one uses its own storage.

I like the latter approach better.

**Comment by tcw165** [comment]
Hi @shankarpdy , @dgutov just answer this question. I want to further explain that `history` mean to have its own storage so that it can provide you a window-local history.
![history screenshot](https://raw.githubusercontent.com/boyw165/history/master/demo/window-local-history.png)

**Comment by dgutov** [comment]
Having your own storage means you can save more things, too. For instance, in `point-stack` I found useful to also save and restore the `window-start` value.

**Comment by tcw165** [comment]
FYI @shankarpdy , I'm implementing following requirement.

> Is there a point in offering specific support for different commands?
