### ISSUE TITLE
Include the current window-start in the history entry?

### ISSUE THREAD

**Issue by dgutov** [boyw165/history#6]
It's quite useful to restore the previous window scroll position, as well as point.

Especially when otherwise point, when restored, would move to somewhere around the bottom of the current window.

**Comment by tcw165** [comment]
Hi @dgutov , it currently supports `window-start` restoring. https://github.com/boyw165/history/commit/374a713d7cd076f990534d5857b6abff253ac586

**Comment by boyw165** [comment]
Hi @dgutov , just submitted. https://github.com/boyw165/history/commit/374a713d7cd076f990534d5857b6abff253ac586

**Comment by dgutov** [comment]
Thanks!
