### ISSUE TITLE
Don't add a new entry when it's the same as the top one

### ISSUE THREAD

**Issue by dgutov** [boyw165/history#7]
To avoid duplicates.

This will be especially useful if you advise core functions to call `history-add-history` automatically.

**Comment by tcw165** [comment]
Thanks, I noticed that too. :dart:

**Comment by tcw165** [comment]
Hi @dgutov 

> Don't add a new entry when it's the same as the top one

I think it is implemented in the latest repo.

> This will be especially useful if you advise core functions to call history-add-history automatically.

Like what core functions?

**Comment by dgutov** [comment]
Thanks!

> Like what core functions?

Well, you've seen [my list](https://github.com/dgutov/point-stack/blob/master/point-stack.el#L33-L36).

Point is, if I've done `isearch-forward`, `C-g`, `isearch-forward` again from the same position, I only want one history entry added.
