### ISSUE TITLE
Remove the entry from previous stack after `history-prev-history`

### ISSUE THREAD

**Issue by dgutov** [boyw165/history#8]
Scenario:
1. `M-x history-add-history`.
2. Move away somewhere. `M-x history-prev-history`.
3. Move to a yet another position. `M-x history-add-history`.

Result: two history entries, the newer after the older.

Expected result: just one history entry, the new one.

**Comment by tcw165** [comment]
Thanks! It was fixed at https://github.com/boyw165/history/commit/d4ad408eb1114e6d7dc6d04f5a1ff872764b1eb6

FYI, history has a convenient trick. If your current point is far away from the latest one, it'll move to the latest one when you ask `history-prev-history`. Just like a hint for prompting people where did they just navigate to.

**Comment by tcw165** [comment]
Hi @dgutov , sorry I was wrong. Previous patch didn't solve the problem and further produced a bigger problem...
Luckily it is solved now. https://github.com/boyw165/history/commit/861f6945d896b2bd3c58a145f680a24a6938143b

**Comment by dgutov** [comment]
Thanks!
